import localFont from 'next/font/local';
import '@/public/assets/css/style.css';
import 'aos/dist/aos.css'
import './globals.css';
import Head from 'next/head';
import { RootNavber } from '@/component/navigation/RootNavbar';
import { Footer } from '@/component/home/Footer';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata = {
  title: ' Bootstrap Template',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <Head>
        <link href='assets/img/favicon.png' rel='icon' />
        <link href='assets/img/apple-touch-icon.png' rel='apple-touch-icon' />
      </Head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <RootNavber />
        <main>{children}</main>
        <Footer />

        {/* <script src='assets/vendor/jquery/jquery.min.js'></script>
        <script src='assets/vendor/bootstrap/js/bootstrap.bundle.min.js'></script>
        <script src='assets/vendor/jquery.easing/jquery.easing.min.js'></script>
        <script src='assets/vendor/isotope-layout/isotope.pkgd.min.js'></script>
        <script src='assets/vendor/venobox/venobox.min.js'></script>
        <script src='assets/vendor/aos/aos.js'></script>
        <script src='assets/js/main.js'></script>
        <script src='assets/vendor/owl.carousel/owl.carousel.min.js'></script> */}
      </body>
    </html>
  );
}
